data_analytics_visualization/data_analytics_visualization/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('results.urls', 'results'), namespace="results")),
    url(r'^tools/', include(('tools.urls', 'tools'), namespace="tools")),
]

data_analytics_visualization/results/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ResultsView.as_view(), name='index'),
    url(r'^ajax/get-entity-details/$', views.get_entity_details, name='get_entity_details'),
    url(r'^complete-data$', views.CompleteDataView.as_view(), name='complete-data'),
    url(r'^complete-data-light$', views.CompleteDataLightView.as_view(), name='complete-data-light'),
    # url(r'^insert-data$', views.InsertDataView.as_view(), name='insert-data'),
]

data_analytics_visualization/tools/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ToolsView.as_view(), name='index'),
    url(r'^ajax/text-tool/$', views.text_tool, name='text_tool'),
]

data_analytics_visualization/results/models.py
from django.db import models


class PuncToken(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class SimpleToken(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class TweetToken(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class StopwordToken(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class LancasterStem(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class PorterStem(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class SnowballStem(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class LemmatizerStem(models.Model):
    token = models.TextField()

    def __str__(self):
        return self.token


class Entity(models.Model):
    entity = models.TextField()
    label = models.TextField()

    def __str__(self):
        return self.entity


class Tweet(models.Model):

    index = models.PositiveIntegerField()
    text = models.TextField()
    text_cleaned = models.TextField()
    punc_tokens = models.ManyToManyField(PuncToken, through="PuncTokenRelation")
    simple_tokens = models.ManyToManyField(SimpleToken, through="SimpleTokenRelation")
    tweet_tokens = models.ManyToManyField(TweetToken, through="TweetTokenRelation")
    stopword_tokens = models.ManyToManyField(StopwordToken, through="StopwordTokenRelation")
    lancaster_stems = models.ManyToManyField(LancasterStem, through="LancasterStemRelation")
    porter_stems = models.ManyToManyField(PorterStem, through="PorterStemRelation")
    snowball_stems = models.ManyToManyField(SnowballStem, through="SnowballStemRelation")
    lemmatizer_stems = models.ManyToManyField(LemmatizerStem, through="LemmatizerStemRelation")
    afinn = models.IntegerField()
    sentiment140 = models.PositiveIntegerField()
    entities = models.ManyToManyField(Entity, through="EntityRelation")

    class Meta:
        index_together = [['index']]

    def __str__(self):
        return self.text


class PuncTokenRelation(models.Model):
    token = models.ForeignKey(PuncToken, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class SimpleTokenRelation(models.Model):
    token = models.ForeignKey(SimpleToken, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class TweetTokenRelation(models.Model):
    token = models.ForeignKey(TweetToken, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class StopwordTokenRelation(models.Model):
    token = models.ForeignKey(StopwordToken, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class LancasterStemRelation(models.Model):
    token = models.ForeignKey(LancasterStem, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class PorterStemRelation(models.Model):
    token = models.ForeignKey(PorterStem, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class SnowballStemRelation(models.Model):
    token = models.ForeignKey(SnowballStem, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class LemmatizerStemRelation(models.Model):
    token = models.ForeignKey(LemmatizerStem, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)


class EntityRelation(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    counter = models.PositiveIntegerField(default=1)

data_analytics_visualization/results/views.py
from ast import literal_eval

from django.db.models import Sum
from django.http import JsonResponse
from django.views.generic import TemplateView

from spacy import displacy
import pandas as pd

from data_analytics_visualization.utils import get_nlp_tweet_to_render_django, datatxt, get_ents_from_tokens
from results.models import EntityRelation, PuncToken, PuncTokenRelation, SimpleToken, SimpleTokenRelation, TweetToken, \
    TweetTokenRelation, StopwordToken, StopwordTokenRelation, LancasterStem, LancasterStemRelation, PorterStem, \
    PorterStemRelation, SnowballStemRelation, SnowballStem, LemmatizerStemRelation

from results.models import Tweet, LemmatizerStem, Entity


class ResultsView(TemplateView):
    template_name = 'results/index.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
    
        negatives = Tweet.objects.filter(sentiment140=0)
        negatives_perc = negatives.count()/Tweet.objects.all().count()
        positives = Tweet.objects.filter(sentiment140=4)
        positives_perc = positives.count()/Tweet.objects.all().count()
        tokens = LemmatizerStem.objects.values('token')\
            .annotate(tweet_count=Sum('lemmatizerstemrelation__counter'))\
            .order_by("-tweet_count")
        positive_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=positives, label="PERSON")\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        negative_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=negatives, label="PERSON")\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        only_positive_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=positives, label="PERSON")\
            .exclude(entity__in=negative_people.values('entity'))\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        only_negative_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=negatives, label="PERSON")\
            .exclude(entity__in=positive_people.values('entity'))\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        positive_not_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=positives)\
            .exclude(label="PERSON")\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        negative_not_people = Entity.objects.values('id', 'entity')\
            .filter(entityrelation__tweet__in=negatives)\
            .exclude(label="PERSON")\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")
        other_entities = Entity.objects.values('id', 'entity')\
            .exclude(label="PERSON")\
            .annotate(entity_count=Sum('entityrelation__counter'))\
            .order_by("-entity_count")

        context['webpage_title'] = 'Analisi esplorativa - Risultati'
        context['pc_labels'] = 'positivi,negativi'
        context['bc_labels'] = str(list(tokens[:10].values_list('token', flat=True)))\
            .replace("', '", ",").replace("['", "").replace("']", "")
        context['bc_data'] = str(list(tokens[:10].values_list('tweet_count', flat=True)))\
            .replace(", ", ",").replace("[", "").replace("]", "")
        context['bc_labels_ex_1'] = str(list(tokens[1:11].values_list('token', flat=True)))\
            .replace("', '", ",").replace("['", "").replace("']", "")
        context['bc_data_ex_1'] = str(list(tokens[1:11].values_list('tweet_count', flat=True)))\
            .replace(", ", ",").replace("[", "").replace("]", "")

        context['other_entities'] = other_entities.order_by("entity")
        context['positive_not_people'] = positive_not_people
        context['negative_not_people'] = negative_not_people
        context['positive_people'] = positive_people
        context['positive_people_sorted'] = positive_people.order_by("entity")
        context['only_positive_people'] = only_positive_people
        context['negative_people'] = negative_people
        context['negative_people_sorted'] = negative_people.order_by("entity")
        context['only_negative_people'] = only_negative_people
        context['tokens'] = tokens
        context['polarity'] = f'{positives_perc},{negatives_perc}'
        context['positives'] = positives
        context['negatives'] = negatives
        return context


def get_entity_details(request):
    entity_id = request.GET.get('entity_id', None)
    tweet = EntityRelation.objects.filter(entity_id=entity_id).first().tweet
    # noinspection PyUnresolvedReferences
    data = {
        'tweet': displacy.render(get_nlp_tweet_to_render_django(tweet),
                                 style='ent', page=True, manual=True),
        'nel': datatxt.nex(tweet.text).annotations
    }
    return JsonResponse(data)


class CompleteDataView(TemplateView):
    template_name = 'results/complete-data.html'

    def get_context_data(self, **kwargs):
        context = super(CompleteDataView, self).get_context_data(**kwargs)

        tweets = Tweet.objects.all().prefetch_related('punc_tokens', 'simple_tokens', 'tweet_tokens', 'stopword_tokens',
                                                    'lancaster_stems', 'porter_stems', 'snowball_stems',
                                                    'lemmatizer_stems', 'entities')

        context['webpage_title'] = 'Analisi esplorativa - Dati completi'

        context['tweets'] = tweets
        return context


class CompleteDataLightView(CompleteDataView):
    template_name = 'results/complete-data-light.html'

    def get_context_data(self, **kwargs):
        context = super(CompleteDataLightView, self).get_context_data(**kwargs)

        context['tweets'] = context['tweets'][:1000]
        return context


class InsertDataView(TemplateView):
    template_name = 'results/index.html'

    def get_context_data(self, **kwargs):
        context = super(InsertDataView, self).get_context_data(**kwargs)

        context['webpage_title'] = 'Analisi esplorativa - Inserimento Dati'


        filename = 'data/dataset_complete.csv'
        data = pd.read_csv(filename)
        data["text_cleaned_punc_tok"] = data["text_cleaned_punc_tok"].apply(literal_eval)
        data["text_cleaned_cleaned_stop"] = data["text_cleaned_stop"].apply(literal_eval)
        data["text_cleaned_stop_punc"] = data["text_cleaned_stop_punc"].apply(literal_eval)
        data["text_cleaned_lanc_stem"] = data["text_cleaned_lanc_stem"].apply(literal_eval)
        data["text_cleaned_port_stem"] = data["text_cleaned_port_stem"].apply(literal_eval)
        data["text_cleaned_snow_stem"] = data["text_cleaned_snow_stem"].apply(literal_eval)
        data["text_cleaned_simple_tok"] = data["text_cleaned_simple_tok"].apply(literal_eval)
        data["text_cleaned_tweet_tok"] = data["text_cleaned_tweet_tok"].apply(literal_eval)
        data["text_cleaned_lem"] = data["text_cleaned_lem"].apply(literal_eval)
        data["ents_tok"] = data["text_cleaned_lem"].apply(get_ents_from_tokens)

        for index, row in data.iterrows():
            tweet, created = Tweet.objects.get_or_create(index=index, text=row['text'], text_cleaned=row['text_cleaned'], afinn=row['afinn'], sentiment140=row['sentiment140'])
            if created:
                for token in row['text_cleaned_punc_tok']:
                    pt, created = PuncToken.objects.get_or_create(token=token)
                    ptr, created = PuncTokenRelation.objects.get_or_create(tweet=tweet, token=pt)
                    if not created:
                        ptr.counter += 1
                        ptr.save()
                for token in row['text_cleaned_simple_tok']:
                    st, created = SimpleToken.objects.get_or_create(token=token)
                    stre, created = SimpleTokenRelation.objects.get_or_create(tweet=tweet, token=st)
                    if not created:
                        stre.counter += 1
                        stre.save()
                for token in row['text_cleaned_tweet_tok']:
                    tt, created = TweetToken.objects.get_or_create(token=token)
                    ttr, created = TweetTokenRelation.objects.get_or_create(tweet=tweet, token=tt)
                    if not created:
                        ttr.counter += 1
                        ttr.save()
                for token in row['text_cleaned_stop_punc']:
                    swt, created = StopwordToken.objects.get_or_create(token=token)
                    swtr, created = StopwordTokenRelation.objects.get_or_create(tweet=tweet, token=swt)
                    if not created:
                        swtr.counter += 1
                        swtr.save()
                for token in row['text_cleaned_lanc_stem']:
                    ls, created = LancasterStem.objects.get_or_create(token=token)
                    lsr, created = LancasterStemRelation.objects.get_or_create(tweet=tweet, token=ls)
                    if not created:
                        lsr.counter += 1
                        lsr.save()
                for token in row['text_cleaned_port_stem']:
                    ps, created = PorterStem.objects.get_or_create(token=token)
                    psr, created = PorterStemRelation.objects.get_or_create(tweet=tweet, token=ps)
                    if not created:
                        psr.counter += 1
                        psr.save()
                for token in row['text_cleaned_snow_stem']:
                    ss, created = SnowballStem.objects.get_or_create(token=token)
                    ssr, created = SnowballStemRelation.objects.get_or_create(tweet=tweet, token=ss)

data_analytics_visualization/templates/results/complete-data-light.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="dashboard-counts section-padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="wrapper count-title text-center">
                        <strong class="text-uppercase">Dati completi</strong>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="dashboard-header section-padding">
        <div class="container-fluid">
            <div class="row d-flex align-items-md-stretch">
                <div class="col col-12">
                    <div class="card">
                        <div class="card-header text-center">
                            <h4>Link alla pagina per la consultazione dei dati completi</h4>
                        </div>
                        <div class="card-body">
                            <div class="col text-center">
                                <button type="button" class="btn btn-primary"
                                        onclick="window.location='{% url 'results:complete-data' %}';">
                                    15000 Tweet
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><section class="dashboard-counts section-padding">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="wrapper count-title text-center">
                    <strong class="text-uppercase">
                        Dati relativi solo ai primi 1000 tweet per alleggerire il caricamento della pagina
                    </strong>
                </div>
            </div>
        </div>
    </div>
</section>
    <section class="dashboard-counts section-padding">
        <div class="container-fluid">
            {% include 'results/complete-data-row.html' %}
        </div>
    </section>
{% endblock %}
{% block custom-scripts %}
    <script src="{% static "js/results/complete-data.js" %}"></script>
{% endblock %}

data_analytics_visualization/templates/results/complete-data-row.html
<div class="row d-flex align-items-md-stretch">
    <div class="col col-12">
        <div class="card">
            <div class="card-header text-center">
                <h4>Tabella per la pulizia del testo</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-2">#</th>
                                <th class="col-5">Tweet</th>
                                <th class="col-5">Text cleaned</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tweets %}
                                <tr class="d-flex">
                                    <th class="col-2" scope="row">{{ item.index }}</th>
                                    <td class="col-5">{{ item.text }}</td>
                                    <td class="col-5">{{ item.text_cleaned }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col col-12">
        <div class="card">
            <div class="card-header text-center">
                <h4>Tabella per il confronto dei tokenizer</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-1">#</th>
                                <th class="col-3">Wordpunc Tokenizer</th>
                                <th class="col-3">Simple Tokenizer</th>
                                <th class="col-3">Tweet Tokenizer</th>
                                <th class="col-2">Stopwords Removal</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tweets %}
                                <tr class="d-flex">
                                    <th class="col-1" scope="row">{{ item.index }}</th>
                                    <td class="col-3">
                                        [{% for token in item.punc_tokens.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-3">
                                        [{% for token in item.simple_tokens.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-3">
                                        [{% for token in item.tweet_tokens.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-2">
                                        [{% for token in item.stopword_tokens.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col col-12">
        <div class="card">
            <div class="card-header text-center">
                <h4>Tabella per il confronto degli Stemmer</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-1">#</th>
                                <th class="col-3">Lancaster Stemmer</th>
                                <th class="col-3">Porter Stemmer</th>
                                <th class="col-3">Snowball Stemmer</th>
                                <th class="col-2">Lemmatizer</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tweets %}
                                <tr class="d-flex">
                                    <th class="col-1" scope="row">{{ item.index }}</th>
                                    <td class="col-3">
                                        [{% for token in item.lancaster_stems.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-3">
                                        [{% for token in item.porter_stems.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-3">
                                        [{% for token in item.snowball_stems.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                    <td class="col-2">
                                        [{% for token in item.lemmatizer_stems.all %}
                                            {% if forloop.last %}
                                                {{ token.token }}
                                            {% else %}
                                                {{ token.token }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col col-12">
        <div class="card">
            <div class="card-header text-center">
                <h4>Tabella per il confronto del sentiment</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="d-flex">
                                <th class="col-1">#</th>
                                <th class="col-5">Tweet</th>
                                <th class="col-1">Afinn</th>
                                <th class="col-2">Sentiment140</th>
                                <th class="col-3">Entities</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tweets %}
                                <tr class="d-flex">
                                    <th class="col-1" scope="row">{{ item.index }}</th>
                                    <td class="col-5">{{ item.text }}</td>
                                    <td class="col-1">{{ item.afinn }}</td>
                                    <td class="col-2">{{ item.sentiment140 }}</td>
                                    <td class="col-3">
                                        [{% for entity in item.entities.all %}
                                            {% if forloop.last %}
                                                {{ entity.entity }}
                                            {% else %}
                                                {{ entity.entity }},
                                            {% endif %}
                                        {% endfor %}]
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

data_analytics_visualization/templates/results/complete-data.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="dashboard-counts section-padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="wrapper count-title text-center">
                        <strong class="text-uppercase">Dati completi</strong>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="dashboard-header section-padding">
        <div class="container-fluid">
            {% include 'results/complete-data-row.html' %}
        </div>
    </section>
{% endblock %}
{% block custom-scripts %}
    <script src="{% static "js/results/complete-data.js" %}"></script>
{% endblock %}

data_analytics_visualization/templates/results/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% include "results/result1.html" %}
    {% include "results/result2.html" %}
    {% include "results/result3.html" %}
    {% include "results/result4.html" %}
    {% include "results/result5.html" %}
{% endblock %}
{% block custom-scripts %}
    <script src="{% static "js/results/index.js" %}"></script>
{% endblock %}