data_analytics_visualization/data_analytics_visualization/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('results.urls', 'results'), namespace="results")),
    url(r'^tools/', include(('tools.urls', 'tools'), namespace="tools")),
]

data_analytics_visualization/results/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ResultsView.as_view(), name='index'),
    url(r'^ajax/get-entity-details/$', views.get_entity_details, name='get_entity_details'),
    url(r'^complete-data$', views.CompleteDataView.as_view(), name='complete-data'),
    url(r'^complete-data-light$', views.CompleteDataLightView.as_view(), name='complete-data-light'),
    # url(r'^insert-data$', views.InsertDataView.as_view(), name='insert-data'),
]

data_analytics_visualization/tools/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ToolsView.as_view(), name='index'),
    url(r'^ajax/text-tool/$', views.text_tool, name='text_tool'),
]

data_analytics_visualization/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ webpage_title }}</title>
        {% block head %}{% endblock %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="all,follow">
        <!-- Bootstrap CSS-->
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <!-- Font Awesome CSS-->
        <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
        <!-- Fontastic Custom icon font-->
        <link rel="stylesheet" href="{% static "css/fontastic.css" %}">
        <!-- Google fonts - Roboto -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
        <!-- jQuery Circle-->
        <link rel="stylesheet" href="{% static "css/grasp_mobile_progress_circle-1.0.0.min.css" %}">
        <!-- Custom Scrollbar-->
        <link rel="stylesheet" href="{% static "css/jquery.mCustomScrollbar.css" %}">
        <!-- theme stylesheet-->
        <link rel="stylesheet" href="{% static "css/style.default.css" %}" id="theme-stylesheet">
        <!-- tables stylesheet-->
        <link rel="stylesheet" href="{% static "css/datatables.min.css" %}">
        <!-- Custom stylesheet - for your changes-->
        <link rel="stylesheet" href="{% static "css/custom.css" %}">
        <!-- Favicon-->
        <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
        <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    </head>
    <body>
        <div id="spinner" class="d-flex justify-content-center">
            <div class="spinner-border" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Side Navbar -->
        <nav class="side-navbar">
            <div class="side-navbar-wrapper">
                <!-- Sidebar Navigation Menus-->
                <div class="main-menu">
                    <h5 class="sidenav-heading"> </h5>
                    <ul id="side-main-menu" class="side-menu list-unstyled">
                        <li><a href="{% url 'results:index' %}"> <i class="icon-home"></i>Risultati</a></li>
                        <li><a href="{% url 'results:complete-data-light' %}"> <i class="icon-grid"></i>Dati completi</a></li>
                        <li><a href="{% url 'tools:index' %}"> <i class="icon-flask"></i>Tools Dinamico</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="page">
            <!-- navbar-->
            <header class="header">
                <nav class="navbar">
                    <div class="container-fluid">
                        <div class="navbar-holder d-flex align-items-center justify-content-between">
                            <div class="navbar-header">
                                <a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a>
                                <a href="{% url 'results:index' %}" class="navbar-brand">
                                    <div class="brand-text d-none d-md-inline-block">
                                        <span>Analisi Esplorativa su tweet relativi al film&nbsp;&nbsp;</span><strong class="text-primary">"Avengers: Endgame"</strong>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>

            {% block content %}{% endblock %}

            <footer class="main-footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <p>Università degli Studi di Milano Bicocca - Alessio Scheri, 858579 &copy; 2020</p>
                        </div>
                        <div class="col-sm-6 text-right">
                            <p>Design by <a href="https://bootstrapious.com/p/bootstrap-4-dashboard" class="external">Bootstrapious</a></p>
                            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <!-- JavaScript files-->
        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
        <script src="{% static "js/grasp_mobile_progress_circle-1.0.0.min.js" %}"></script>
        <script src="{% static "js/jquery.cookie.js" %}"> </script>
        <script src="{% static "js/Chart.min.js" %}"></script>
{#        <script src="vendor/jquery-validation/jquery.validate.min.js"></script>#}
        <script src="{% static "js/jquery.mCustomScrollbar.concat.min.js" %}"></script>
        <script src="{% static "js/datatables.min.js" %}"></script>
        <script src="{% static "js/charts-home.js" %}"></script>
        <!-- Main File-->
        <script src="{% static "js/front_theme.js" %}"></script>
        {% block custom-scripts %}{% endblock %}
    </body>
</html>